name: Daily update
on:
  schedule:
    - cron: '30 4 * * *'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v31

      - name: Setup git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update package dependencies
        run: |
          # Until [bundix#68](https://github.com/nix-community/bundix/pull/68) is resolved
          nix develop -c bash -lc '
            bundle config set --local force_ruby_platform true
            rm -f gemset.nix Gemfile.lock
            bundle lock --add-platform ruby
            BUNDLE_FORCE_RUBY_PLATFORM=true bundix -l
          '

          git add gemset.nix Gemfile.lock
          git diff --cached --quiet && exit 0

          msg="$(mktemp)"
          trap 'rm -f "$msg"' EXIT
          printf 'Update dependencies\n' > "$msg"
          git commit -F "$msg"

      - name: Push updates
        run: |
          git push origin HEAD:master
