name: RSpec
on:
  push:

permissions:
  contents: read

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31

      - name: Run RSpec
        run: nix develop -c bundle exec rspec
